Refactoring the Transaction class.
yiisoft/db pull request #191
Opened 2020-10-22 22:57 UTC by mj4444ru

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

2020-10-29 17:45 UTC, mj4444ru commented on src/Transaction/Transaction.php
> +    public const TIL_READ_UNCOMMITTED = 'READ UNCOMMITTED';
When we create a constant for the `status` field, we call it `STATUS_ACTIVE`, but not `ACTIVE`.
The `SERIALIZABLE` style constants imported into the local scope can be confusing to me.
**TIL** - stands for **T**ransaction **I**solation **L**evel.

This is just a suggestion. It is possible to return constants without a prefix.

2020-10-29 17:50 UTC, mj4444ru commented on src/Transaction/Transaction.php
> +    public const TIL_READ_UNCOMMITTED = 'READ UNCOMMITTED';
When we create a constant for the `status` field, we call it` STATUS_ACTIVE`, but not ʻACTIVE`.
**TIL** stands for **T**ransaction **I**solation **L**evel.

**TIL_** is probably a bad option for a prefix. Can be changed to **IL_** (**I**solation **L**evel), or **LEVEL_**.

This is just a suggestion. It is possible to return constants without a prefix.

2020-10-29 18:01 UTC, samdark commented on src/Transaction/Transaction.php
> +    public const TIL_READ_UNCOMMITTED = 'READ UNCOMMITTED';
OK but there are already constants for the purpose, aren't there?

2020-10-29 20:21 UTC, mj4444ru commented on src/Transaction/Transaction.php
> +    public const TIL_READ_UNCOMMITTED = 'READ UNCOMMITTED';
I thought that they can be left for compatibility with yii2 and marked as deprecated), while in yii3 to encourage the use of new constants.

Your opinion?

2020-10-29 20:39 UTC, samdark commented on src/Transaction/Transaction.php
> +    public const TIL_READ_UNCOMMITTED = 'READ UNCOMMITTED';
We don't need to take care compatibiltiy too much and definitely don't want deprecated stuff in Yii 3 v1.0.

2020-10-29 22:57 UTC, mj4444ru commented on src/Transaction/Transaction.php
> +    public const TIL_READ_UNCOMMITTED = 'READ UNCOMMITTED';
In this case, I suggest choosing a prefix between **IL_** and **LEVEL**. And remove constants without a prefix.

2020-10-30 07:37 UTC, samdark commented on src/Transaction/Transaction.php
> +    public const TIL_READ_UNCOMMITTED = 'READ UNCOMMITTED';
LEVEL is better.

2020-11-06 14:58 UTC, samdark requested changes

2020-11-06 14:58 UTC, samdark commented on src/Transaction/Transaction.php
> +    public const LEVEL_READ_UNCOMMITTED = 'READ UNCOMMITTED';
It's used in ConnectionTest. Should be renamed there as well.

2020-11-06 14:58 UTC, samdark commented on src/Transaction/Transaction.php
> +    public const LEVEL_READ_UNCOMMITTED = 'READ UNCOMMITTED';
It's used in sqlite and pgsql driver packages.

2021-09-29 22:29 UTC, terabytesoftw commented
closed due to inactivity

2021-09-29 22:29 UTC, closed without merging