Add contexts for profiler
yiisoft/db pull request #568
Opened 2023-03-04 13:47 UTC by darkdef

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️

2023-03-05 11:23 UTC, xepozz requested changes

2023-03-05 11:23 UTC, xepozz commented on src/Profiler/ContextInterface.php
> +    public function __toArray(): array;
Why with `__` prefix?

2023-03-05 11:23 UTC, xepozz commented on src/Profiler/ContextInterface.php
> +    public function setException(Throwable $e): static;
What the reason to have it in the interface?

2023-03-07 17:39 UTC, darkdef commented on src/Profiler/ContextInterface.php
> +    public function __toArray(): array;
fixed

2023-03-08 06:58 UTC, xepozz approved these changes

2023-03-08 18:36 UTC, merged