Remove legacy sintax.
yiisoft/db pull request #722
Opened 2023-06-12 12:12 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

2023-06-18 15:04 UTC, vjik requested changes

2023-06-18 15:19 UTC, vjik requested changes
Need changelog

2023-06-18 15:44 UTC, terabytesoftw commented on composer.json
> +        "yiisoft/cache": "^2.0",
in another pr.

2023-06-18 15:47 UTC, vjik approved these changes

2023-06-18 15:51 UTC, vjik commented on CHANGELOG.md
> +- Bug #722: Remove legacy sintaxis for array typecast in Param class. (@terabytesoftw)
```suggestion
- Chg #722: Remove legacy array syntax for typecast. Use `Param` instead (@terabytesoftw)
```

Need verify.

2023-06-18 15:52 UTC, vjik commented on CHANGELOG.md
> +- Bug #722: Remove legacy sintaxis for array typecast in Param class. (@terabytesoftw)
Is major change?

2023-06-18 17:09 UTC, darkdef commented on CHANGELOG.md
> +- Bug #722: Remove legacy sintaxis for array typecast in Param class. (@terabytesoftw)
I think - no. It's remove unused code

2023-06-18 17:09 UTC, darkdef approved these changes

2023-06-20 14:06 UTC, samdark approved these changes

2023-06-20 14:07 UTC, merged

2023-06-20 14:07 UTC, samdark commented
👍