Fix psalm issues
yiisoft/db pull request #802
Opened 2024-01-30 10:35 UTC by Tigrov

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2024-01-31 06:53 UTC, vjik requested changes
Looks good. It remains is adding a line to changelog.

2024-01-31 18:35 UTC, darkdef approved these changes

2024-02-02 18:22 UTC, vjik approved these changes

2024-02-02 18:22 UTC, vjik commented on CHANGELOG.md
> +- Enh #802: Resolve psalm issues (@Tigrov)
```suggestion
- Enh #802: Minor refactoring of `SchemaCache`, `AbstractPdoCommand` and `AbstractDDLQueryBuilder` (@Tigrov)
```

"Resolve psalm issues" is not about public interface of package and too common description of changes. Suggest replace it to refactoring...

2024-02-03 13:24 UTC, merged