translation into Brazilian Portuguese and corrections in the English …
yiisoft/db pull request #819
Opened 2024-04-09 15:36 UTC by luizcmarin

…translation

Two changes are worth highlighting:
- creation of "guide" folder and translations moved there (as standard for documents)
- corrections of links and other 'little things' in English

Furthermore, all links have been verified. 🥴

2024-04-13 06:56 UTC, vjik approved these changes

2024-04-17 06:27 UTC, samdark requested changes
https://github.com/yiisoft/db/actions/runs/8691874638/job/23835161447?pr=819#step:6:33

2024-04-17 10:49 UTC, luizcmarin commented
> https://github.com/yiisoft/db/actions/runs/8691874638/job/23835161447?pr=819#step:6:33

??  I didn't understand

2024-04-17 11:08 UTC, luizcmarin commented
> https://github.com/yiisoft/db/actions/runs/8691874638/job/23835161447?pr=819#step:6:33

I don't feel comfortable dealing with this type of file. Please guide me.

"WARNINGS!
Tests: 790, Assertions: 1587, Warnings: 1, Deprecations: 3."

2024-04-22 20:52 UTC, samdark approved these changes

2024-04-22 20:52 UTC, samdark commented on docs/guide/en/testing.md
> +```dockerfile
```suggestion
```shell
```

2024-04-22 20:52 UTC, merged