Rename `batchInsert()` to `insertBatch()` and change paremeters order
yiisoft/db pull request #829
Opened 2024-04-28 07:07 UTC by Tigrov

* Rename `batchInsert()` to `insertBatch()` in `DMLQueryBuilderInterface` and `CommandInterface`
* Change parameters order to from `$table, $columns, $rows` to `$table, $rows, $columns`
* Add default value `[]` for `$columns` parameter

From `batchInsert(string $table, array $columns, iterable $rows)`
to `insertBatch(string $table, iterable $rows, array $columns = [])`

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  | #772

2024-04-30 13:38 UTC, vjik requested changes
Add info to UPGRADE.md

2024-04-30 13:38 UTC, vjik commented on src/Command/AbstractCommand.php
> +     * @deprecated Use (@see insertBatch()) instead. It will be removed in version 3.0.0.
After merge PR need to create new issue about remove it.

2024-04-30 13:38 UTC, vjik commented on src/QueryBuilder/AbstractDMLQueryBuilder.php
> +     * @deprecated Use (@see insertBatch()) instead. It will be removed in version 3.0.0.
After merge PR need to create new issue about remove it.

2024-05-01 16:03 UTC, Tigrov commented
> Add info to UPGRADE.md and changelog

Done

2024-05-01 16:05 UTC, vjik approved these changes

2024-05-01 16:05 UTC, vjik commented on CHANGELOG.md
> +  and change parameters order from `$table, $columns, $rows` to `$table, $rows, $columns = []` (@Tigrov)
```suggestion
  and change parameters from `$table, $columns, $rows` to `$table, $rows, $columns = []` (@Tigrov)
```

2024-05-05 08:05 UTC, merged